# Generated by Django 4.2.7 on 2026-01-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=100)),
                ('lab_title', models.CharField(max_length=255)),
                ('lab_category', models.CharField(blank=True, max_length=100)),
                ('overall_score', models.IntegerField(default=0)),
                ('code_quality', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('grading_result', models.JSONField(default=dict)),
                ('code_content', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Submission',
                'verbose_name_plural': 'Lab Submissions',
                'db_table': 'lab_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'lab_id')},
            },
        ),
    ]
