# Generated by Django 4.2.7 on 2026-01-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_labsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.IntegerField()),
                ('assessment_title', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('passing_score', models.IntegerField(default=80)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'db_table': 'assessment_results',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'assessment_id')},
            },
        ),
    ]
