# Generated by Django 4.2.7 on 2026-02-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_assessmentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('total_questions', models.IntegerField(default=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('questions', models.JSONField(default=list)),
                ('student_answers', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'db_table': 'exam_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
